"""Typed representations of network elements and their configuration.

The models mirror ``docs/schema.md`` one-to-one:

* :class:`Metadata` and :class:`ElementBase` -- the document envelope (§3).
* :class:`Interface` and friends -- RFC 8343 / RFC 8344 / 802.1Q data (§6.2).
* :class:`Device` and its five kinds, :class:`Cable`, :class:`Adapter` (§6-§8)
  and :class:`Tunnel`, the logical counterpart of a cable (§14).
* :class:`User` and :class:`Group` -- who the network is for, and who may touch
  it (§19).
* :data:`Element` -- the discriminated union on ``kind``.

:func:`parse_document` is the entry point the loader uses; it raises
:class:`~netgraph.errors.SchemaError` with the field path of every offending
value.

Models are *normalising*: MAC addresses, IP addresses, VLAN sets and bit rates
are stored in canonical form and defaults are materialised on load, so a
document and its parsed form describe exactly the same network (§1).
"""

from __future__ import annotations

from netgraph.errors import SchemaError, SchemaIssue
from netgraph.models.adapter import (
    ADAPTER_INTERFACE_TYPES,
    Adapter,
    AdapterSpec,
    UpstreamPort,
    UpstreamType,
)
from netgraph.models.annotation import (
    ANNOTATION_KINDS,
    BORDER_STYLES,
    COHERENCE_RULE,
    COLOUR_PATTERN,
    CORNERS,
    MAX_LEGEND_ENTRIES,
    MAX_MEMBERS,
    MAX_TEXT_LENGTH,
    SWATCH_SHAPES,
    VALUE_RULE,
    Annotation,
    AnnotationBase,
    AnnotationGeometry,
    AnnotationSpecBase,
    Area,
    AreaSelector,
    AreaSpec,
    Legend,
    LegendEntry,
    LegendSpec,
    Note,
    NoteAnchor,
    NoteSpec,
)
from netgraph.models.base import NetgraphModel
from netgraph.models.cable import Cable, CableSpec, Duplex, InterfaceRef, Medium
from netgraph.models.device import (
    DEVICE_KINDS,
    GLOBAL_VRF,
    BridgeConfig,
    BridgeType,
    Computer,
    Device,
    DeviceSpec,
    Forwarding,
    Hub,
    Router,
    Server,
    Switch,
    VlanDefinition,
)
from netgraph.models.document import (
    ANNOTATION_MODELS,
    ELEMENT_MODELS,
    Element,
    annotation_model_for,
    element_model_for,
    parse_annotation,
    parse_document,
    parse_layout,
    parse_template,
    parse_test_suite,
)
from netgraph.models.element import (
    ANNOTATION_DOCUMENT_KINDS,
    AREA_KIND,
    DOCUMENT_KINDS,
    KINDS,
    LAYOUT_KIND,
    LEGEND_KIND,
    NOTE_KIND,
    TEMPLATE_KIND,
    TEST_SUITE_KIND,
    ElementBase,
)
from netgraph.models.identity import (
    EMAIL_PATTERN,
    GROUP_KIND,
    IDENTITY_KINDS,
    LOGIN_PATTERN,
    MAX_EMAIL_LENGTH,
    MAX_GROUP_MEMBERS,
    MAX_LOGIN_LENGTH,
    MAX_POSIX_ID,
    MAX_SSH_KEYS,
    USER_KIND,
    EmailAddress,
    Group,
    GroupSpec,
    Login,
    PosixId,
    SshPublicKey,
    User,
    UserSpec,
    UserStatus,
    UserType,
)
from netgraph.models.interface import (
    AGGREGATE_TYPES,
    CABLEABLE_TYPES,
    CHANNEL_WIDTHS,
    AcceptableFrames,
    Band,
    Bss,
    Interface,
    InterfaceType,
    IPv4Address,
    IPv4Config,
    IPv6Address,
    IPv6Config,
    RadioRole,
    Security,
    VlanConfig,
    VlanMode,
    WirelessConfig,
)
from netgraph.models.layout import (
    LAYOUT_VIEWS,
    EdgeGeometry,
    GroupGeometry,
    LabelGeometry,
    Layout,
    LayoutSpec,
    NodeGeometry,
    Point,
    Size,
    ViewGeometry,
)
from netgraph.models.metadata import RESERVED_LABEL_PREFIX, Location, Metadata
from netgraph.models.patchpanel import (
    FRONT,
    MAX_PANEL_PORTS,
    PATCHPANEL_KIND,
    REAR,
    PanelSide,
    PatchPanel,
    PatchPanelSpec,
    panel_port,
    parse_port_range,
    split_panel_port,
)
from netgraph.models.pdu import (
    MAX_PDU_OUTLETS,
    PDU_KIND,
    Pdu,
    PduSpec,
    parse_outlet_range,
)
from netgraph.models.power import (
    MAX_POWER_INPUTS,
    POE_CLASS_MAX,
    POE_PD_WATTS,
    POE_PSE_WATTS,
    PoeConfig,
    PoeStandard,
    PowerConfig,
    PowerDraw,
    PowerInput,
    PowerSource,
    format_watts,
)
from netgraph.models.routing import (
    ASN_MAX,
    Asn,
    BgpConfig,
    BgpNeighbor,
    OspfConfig,
    RoutingConfig,
    StaticRoute,
    VrfDefinition,
)
from netgraph.models.scalars import (
    API_VERSION,
    VlanSet,
    format_bitrate,
    normalise_mac,
    parse_bitrate,
)
from netgraph.models.template import INHERIT_KEY, TEMPLATE_SPEC_KEYS, Template
from netgraph.models.testsuite import (
    MAX_ASSERTIONS,
    REACHABILITY_ASSERTIONS,
    SELECTOR_ASSERTIONS,
    Assertion,
    AssertionLayer,
    AssertionType,
    TestSuite,
    TestSuiteSpec,
)
from netgraph.models.tunnel import (
    MAX_VNI,
    Tunnel,
    TunnelAuth,
    TunnelMode,
    TunnelSpec,
    TunnelTransport,
    TunnelType,
)

__all__ = [
    "ADAPTER_INTERFACE_TYPES",
    "AGGREGATE_TYPES",
    "ANNOTATION_DOCUMENT_KINDS",
    "ANNOTATION_KINDS",
    "ANNOTATION_MODELS",
    "API_VERSION",
    "AREA_KIND",
    "ASN_MAX",
    "BORDER_STYLES",
    "CABLEABLE_TYPES",
    "CHANNEL_WIDTHS",
    "COHERENCE_RULE",
    "COLOUR_PATTERN",
    "CORNERS",
    "DEVICE_KINDS",
    "DOCUMENT_KINDS",
    "ELEMENT_MODELS",
    "EMAIL_PATTERN",
    "FRONT",
    "GLOBAL_VRF",
    "GROUP_KIND",
    "IDENTITY_KINDS",
    "INHERIT_KEY",
    "KINDS",
    "LAYOUT_KIND",
    "LAYOUT_VIEWS",
    "LEGEND_KIND",
    "LOGIN_PATTERN",
    "MAX_ASSERTIONS",
    "MAX_EMAIL_LENGTH",
    "MAX_GROUP_MEMBERS",
    "MAX_LEGEND_ENTRIES",
    "MAX_LOGIN_LENGTH",
    "MAX_MEMBERS",
    "MAX_PANEL_PORTS",
    "MAX_PDU_OUTLETS",
    "MAX_POSIX_ID",
    "MAX_POWER_INPUTS",
    "MAX_SSH_KEYS",
    "MAX_TEXT_LENGTH",
    "MAX_VNI",
    "NOTE_KIND",
    "PATCHPANEL_KIND",
    "PDU_KIND",
    "POE_CLASS_MAX",
    "POE_PD_WATTS",
    "POE_PSE_WATTS",
    "REACHABILITY_ASSERTIONS",
    "REAR",
    "RESERVED_LABEL_PREFIX",
    "SELECTOR_ASSERTIONS",
    "SWATCH_SHAPES",
    "TEMPLATE_KIND",
    "TEMPLATE_SPEC_KEYS",
    "TEST_SUITE_KIND",
    "USER_KIND",
    "VALUE_RULE",
    "AcceptableFrames",
    "Adapter",
    "AdapterSpec",
    "Annotation",
    "AnnotationBase",
    "AnnotationGeometry",
    "AnnotationSpecBase",
    "Area",
    "AreaSelector",
    "AreaSpec",
    "Asn",
    "Assertion",
    "AssertionLayer",
    "AssertionType",
    "Band",
    "BgpConfig",
    "BgpNeighbor",
    "BridgeConfig",
    "BridgeType",
    "Bss",
    "Cable",
    "CableSpec",
    "Computer",
    "Device",
    "DeviceSpec",
    "Duplex",
    "EdgeGeometry",
    "Element",
    "ElementBase",
    "EmailAddress",
    "Forwarding",
    "Group",
    "GroupGeometry",
    "GroupSpec",
    "Hub",
    "IPv4Address",
    "IPv4Config",
    "IPv6Address",
    "IPv6Config",
    "Interface",
    "InterfaceRef",
    "InterfaceType",
    "LabelGeometry",
    "Layout",
    "LayoutSpec",
    "Legend",
    "LegendEntry",
    "LegendSpec",
    "Location",
    "Login",
    "Medium",
    "Metadata",
    "NetgraphModel",
    "NodeGeometry",
    "Note",
    "NoteAnchor",
    "NoteSpec",
    "OspfConfig",
    "PanelSide",
    "PatchPanel",
    "PatchPanelSpec",
    "Pdu",
    "PduSpec",
    "PoeConfig",
    "PoeStandard",
    "Point",
    "PosixId",
    "PowerConfig",
    "PowerDraw",
    "PowerInput",
    "PowerSource",
    "RadioRole",
    "Router",
    "RoutingConfig",
    "SchemaError",
    "SchemaIssue",
    "Security",
    "Server",
    "Size",
    "SshPublicKey",
    "StaticRoute",
    "Switch",
    "Template",
    "TestSuite",
    "TestSuiteSpec",
    "Tunnel",
    "TunnelAuth",
    "TunnelMode",
    "TunnelSpec",
    "TunnelTransport",
    "TunnelType",
    "UpstreamPort",
    "UpstreamType",
    "User",
    "UserSpec",
    "UserStatus",
    "UserType",
    "ViewGeometry",
    "VlanConfig",
    "VlanDefinition",
    "VlanMode",
    "VlanSet",
    "VrfDefinition",
    "WirelessConfig",
    "annotation_model_for",
    "element_model_for",
    "format_bitrate",
    "format_watts",
    "normalise_mac",
    "panel_port",
    "parse_annotation",
    "parse_bitrate",
    "parse_document",
    "parse_layout",
    "parse_outlet_range",
    "parse_port_range",
    "parse_template",
    "parse_test_suite",
    "split_panel_port",
]
