"""Per-device scripts: the artefact somebody actually pastes into a session.

``--out DIR`` writes one ``.txt`` per element, under a directory named after the
element's fully-qualified name, exactly as ``netgraph export config --out``
lays out generated configuration. The tree is therefore shaped like the
inventory tree, which is what makes ``diff -r`` between two runs readable, and
two elements cannot collide because a fully-qualified name is unique.

**They are ``.txt`` and not ``.sh``, and that is the point.** netgraph does not
open a session, does not know the device's authentication, and has no idea
whether the box speaks any of this. A file with a shebang and an executable bit
invites somebody to run it against an estate without reading it; a ``.txt``
invites them to read it. The commands are still the exact lines to run, and a
transport built later can consume the JSON plan rather than parsing these.

Every script leads with the same header: the element, the dialect, the capture
it was derived from, the count of changes and how many are disruptive. Then one
block per change, introduced by the drift finding that asked for it, so a
reviewer scrolling the middle of a long script can still see *why* a line is
there.

``--rollback`` writes the same tree from the inverse commands
(:func:`netgraph.converge.commands.revert`), which take the device back to the
state the capture found -- not to some previous plan, and not to a state nobody
measured.
"""

from __future__ import annotations

from collections.abc import Iterator, Sequence
from pathlib import Path
from typing import Final

from netgraph import __version__
from netgraph.converge.model import (
    Command,
    ConvergeChange,
    ConvergePlan,
    DeviceConverge,
    Risk,
)
from netgraph.export.config.model import device_directory
from netgraph.fsio import write_text

__all__ = ["SCRIPT_SUFFIX", "script_files", "script_for", "write_scripts"]

#: What a per-device script is called under its element's directory.
SCRIPT_SUFFIX: Final = "converge.txt"

#: What the inverse script is called. A different name rather than a different
#: directory, so the two sit side by side and a reviewer comparing them does not
#: have to hold two paths in their head.
ROLLBACK_SUFFIX: Final = "rollback.txt"


def script_files(plan: ConvergePlan, *, rollback: bool = False) -> Iterator[tuple[str, str]]:
    """``(path relative to --out, content)`` for every element with commands.

    An element whose changes are all manual gets no file: a script with nothing
    to run in it is a file somebody has to open to find out it is empty.
    """
    suffix = ROLLBACK_SUFFIX if rollback else SCRIPT_SUFFIX
    for device in plan.devices:
        text = script_for(plan, device, rollback=rollback)
        if text is None:
            continue
        yield f"{device_directory(device.element)}/{suffix}", text


def write_scripts(
    plan: ConvergePlan, directory: Path, *, rollback: bool = False
) -> tuple[str, ...]:
    """Write every script under ``directory``. Returns the paths written, in order."""
    written: list[str] = []
    for relative, content in script_files(plan, rollback=rollback):
        target = directory / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        write_text(target, content)
        written.append(relative)
    return tuple(written)


def script_for(
    plan: ConvergePlan,
    device: DeviceConverge,
    *,
    rollback: bool = False,
) -> str | None:
    """One element's script, or ``None`` when it has nothing to run."""
    blocks = [
        change for change in device.changes if (change.rollback if rollback else change.commands)
    ]
    if not blocks:
        return None
    lines = [*_header(plan, device, blocks, rollback=rollback)]
    for change in blocks:
        lines.extend(_block(change, rollback=rollback))
    manual = device.manual
    if manual:
        lines.append("# Not in this script -- these need a person:")
        for change in manual:
            lines.append(f"#   - {change.note or change.summary}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _header(
    plan: ConvergePlan,
    device: DeviceConverge,
    blocks: Sequence[ConvergeChange],
    *,
    rollback: bool,
) -> Iterator[str]:
    what = "rollback" if rollback else "converge"
    disruptive = sum(1 for change in blocks if change.risk is Risk.DISRUPTIVE)
    yield "# Generated by 'netgraph converge plan' -- read before running."
    yield f"# netgraph {__version__}. Not applied by netgraph: it opens no session to a device."
    yield f"# netgraph-script: {what}"
    yield f"# netgraph-element: {device.element} ({device.kind or 'unknown kind'})"
    yield f"# netgraph-dialect: {plan.dialect}"
    for name in plan.inputs:
        yield f"# netgraph-capture: {name}"
    if device.batch is not None:
        yield f"# netgraph-batch: {device.batch}"
    yield "#"
    if rollback:
        yield "# These commands put the device back the way the capture found it."
    else:
        yield "# These commands move the device from what the capture found to what the"
        yield "# inventory declares. They are in dependency order: run them top to bottom."
    if disruptive:
        yield (
            f"# {disruptive} of them is disruptive -- it touches the path this device is"
            if disruptive == 1
            else f"# {disruptive} of them are disruptive -- they touch the path this device is"
        )
        yield "# managed on. Have a console or an out-of-band route before you start."
    yield ""


def _block(change: ConvergeChange, *, rollback: bool) -> Iterator[str]:
    marker = " [DISRUPTIVE]" if change.risk is Risk.DISRUPTIVE else ""
    yield f"# {change.summary}{marker}"
    for entry in change.provenance:
        yield f"#   drift: {entry.location} -- {entry.message}"
    if change.risk is Risk.DISRUPTIVE and change.risk_reason:
        yield f"#   risk: {change.risk_reason}"
    for command in change.rollback if rollback else change.commands:
        yield from _command(command)
    yield ""


def _command(command: Command) -> Iterator[str]:
    yield from command.script_lines()
