"""A regression guard on the cost of loading an inventory.

``load_tree`` is the stage every command pays for, and two rounds of work have
gone into it (entries 1 and 5 of ``docs/follow-ups.md``). This file stops that
work from being given back unnoticed.

**What is measured, and why it is a ratio.** A wall-clock ceiling in
milliseconds would be worthless here: a shared CI runner varies by more between
two runs of the same commit than any regression this guard is meant to catch,
so the threshold would have to be so generous that it caught nothing. What is
stable across machines is the *shape* of the work — so the test measures two
things in the same process, back to back, on the same tree:

``floor``
    Reading and parsing every document and throwing the result away:
    :func:`~netgraph.loader.documents.read_documents` over the whole tree. This
    is PyYAML's cost, which netgraph does not own.

``full``
    The same tree through :func:`~netgraph.loader.load_tree`: the parse, plus
    pydantic model validation, plus the loader's own bookkeeping.

``full / floor`` is then how much netgraph adds on top of parsing, expressed in
units of the parse itself. Machine speed cancels out of the ratio, and so does
most of the noise, because both halves are slow or fast together.

**The thresholds.** They are deliberately per-parser, because the denominator
differs by a factor of eight between the two:

=============  ===============  ==========  =========
Parser         Before entry 5   Today       Threshold
=============  ===============  ==========  =========
libyaml        1.78-1.79        1.52-1.53   1.70
pure Python    1.16             1.10-1.12   1.25
=============  ===============  ==========  =========

The libyaml row is the guard that does the work, and it was checked in both
directions: it passes on this commit and fails on its parent, quoting 1.79.
The margin either side is real but not generous — roughly 11 % of headroom
above today and 5 % below a full revert — which is the price of a guard sharp
enough to notice anything.

The pure-Python row is honestly weaker. With a parse eight times slower in the
denominator, the model layer would have to roughly triple before the ratio
moved as far as its threshold, so this row would *not* catch a revert of entry
5. It is kept because a catastrophic regression should not be invisible on the
fallback path, not because it is sharp.

If this test starts failing on a platform without a code change behind it, the
right fix is to raise the number here *and say so in* ``docs/follow-ups.md`` —
not to delete the guard.
"""

from __future__ import annotations

import importlib.util
import sys
import time
from collections.abc import Callable
from pathlib import Path
from types import ModuleType

import pytest

from netgraph.loader import load_tree
from netgraph.loader.documents import HAVE_LIBYAML, StrictSafeLoader, read_documents
from netgraph.loader.tree import InventoryFile, iter_inventory_files

REPO_ROOT = Path(__file__).resolve().parent.parent
HARNESS = REPO_ROOT / "tools" / "bench_pipeline.py"

#: ``full / floor`` ceilings, keyed by whether libyaml is the parser in use.
#: See the module docstring for where the numbers come from.
MAX_LOAD_RATIO_LIBYAML = 1.70
MAX_LOAD_RATIO_PURE_PYTHON = 1.25

#: How many rounds the two halves are timed for. The *minimum* of each is
#: taken, not the mean: a timing sample is bounded below by the real cost and
#: unbounded above by whatever else the machine was doing, so the smallest
#: sample is the least contaminated one.
SAMPLES = 4


def load_harness() -> ModuleType:
    """Import ``tools/bench_pipeline.py`` as a module.

    The tree is generated by the same code that produces the numbers in
    ``docs/follow-ups.md``; a guard measured on a differently-shaped inventory
    could not be compared with the table it is guarding.
    """
    name = "bench_pipeline"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, HARNESS)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def benchmark_tree(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A scaled-down copy of the benchmark inventory: 80 devices, 158 documents.

    Small enough that the suite does not slow down noticeably even on the
    pure-Python parser, large enough that the fixed costs of the walk itself
    (one ``scandir`` per directory) do not dominate the ratio.
    """
    harness = load_harness()
    root = tmp_path_factory.mktemp("benchmark-inventory")
    shape = harness.Shape(sites=2, racks_per_site=3, hosts_per_rack=12)
    harness.generate(root, shape)
    return root


def milliseconds(call: Callable[[], object]) -> float:
    """Time one call, in milliseconds."""
    start = time.perf_counter()
    call()
    return (time.perf_counter() - start) * 1000


def interleaved_best(
    first: Callable[[], object], second: Callable[[], object], *, samples: int = SAMPLES
) -> tuple[float, float]:
    """Time both calls once per round, ``samples`` rounds; return the two minima.

    Interleaved rather than one after the other, because the two numbers are
    only compared with each other: if the machine stalls for a moment, a round
    that measures both halves during the stall inflates both and the ratio
    survives, where timing all of one and then all of the other would inflate
    just one of them and produce a spurious failure.
    """
    firsts, seconds = [], []
    for _ in range(samples):
        firsts.append(milliseconds(first))
        seconds.append(milliseconds(second))
    return min(firsts), min(seconds)


def parse_floor(files: list[InventoryFile]) -> None:
    """Parse every document and discard it: the cost netgraph does not own."""
    for entry in files:
        for _ in read_documents(entry.path, relative=entry.relative):
            pass


def test_the_generated_tree_is_the_shape_the_guard_assumes(benchmark_tree: Path) -> None:
    """A guard on a tree that silently shrank to nothing would pass forever."""
    inventory = load_tree(benchmark_tree)

    assert not inventory.errors, inventory.errors[:3]
    assert len(inventory) == 158
    assert len(inventory.devices) == 80


def test_loading_costs_no_more_than_its_budget_above_the_parse(benchmark_tree: Path) -> None:
    """``load_tree`` stays within its documented multiple of the raw parse."""
    files = iter_inventory_files(benchmark_tree)

    def parse() -> None:
        parse_floor(files)

    def load() -> None:
        load_tree(benchmark_tree)

    # The tree was written moments ago, so the first pass over it also pays for
    # a cold page cache and for every lazily-built pydantic validator. Warm
    # both halves before anything is timed.
    for _ in range(2):
        parse()
        load()

    floor, full = interleaved_best(parse, load)
    ratio = full / floor

    libyaml_in_use = HAVE_LIBYAML and StrictSafeLoader.__name__ == "CStrictSafeLoader"
    budget = MAX_LOAD_RATIO_LIBYAML if libyaml_in_use else MAX_LOAD_RATIO_PURE_PYTHON

    assert ratio <= budget, (
        f"load_tree is {ratio:.2f}x the raw parse ({full:.1f} ms against {floor:.1f} ms) "
        f"through {StrictSafeLoader.__name__}, over the budget of {budget:.2f}x. Either "
        f"an optimisation from docs/follow-ups.md was undone, or new per-document work "
        f"was added to the loader or the models. Profile with 'python tools/bench_pipeline.py' "
        f"before changing this threshold."
    )
