"""One-click repairs: what each producer offers, and the promise none may break.

Three layers are asserted here, and the third is the one the feature stands on:

**What a producer offers.** One test per fixable rule, on the fixture that
provokes it, checking the operations and — for a rule with more than one reading
— that both are offered and neither is chosen.

**What the loop does with them.** ``repair`` applies one fix at a time against
the tree the previous one left, so two findings in one document do not undo each
other, and a repair that would make things worse is rolled back to the byte.

**The invariant.** *A fix never introduces a finding.* Asserted by re-validating
after every repair — over the example inventories, over every fixture in
``tests/fixtures/``, and over inventories nobody wrote, generated by the
Hypothesis strategies in ``tests/strategies.py`` and deliberately spoiled with a
defect a producer can see.
"""

from __future__ import annotations

from collections import Counter
from collections.abc import Iterator, Sequence
from dataclasses import replace
from pathlib import Path
from typing import Any, Final

import pytest
from hypothesis import HealthCheck, assume, given, settings
from hypothesis import strategies as st

from netgraph.edit import AppendItem, EditError, EditSession, SetGeometry, UnsetField
from netgraph.fixes import (
    FIXES,
    Fix,
    apply_fix,
    fixes_for,
    offers_for,
    producer_for,
    repair,
    spec_for,
)
from netgraph.loader import Inventory, load_tree
from netgraph.rules import RULES, rule_for
from netgraph.validate import Finding, validate

import strategies as ng  # isort: skip -- tests/ is on sys.path, not a package

REPO_ROOT: Final = Path(__file__).resolve().parent.parent
EXAMPLES: Final = REPO_ROOT / "examples"
FIXTURES: Final = REPO_ROOT / "tests" / "fixtures"
INVALID: Final = FIXTURES / "invalid"
#: A small tree whose only problems are fixable ones, two of them in one file.
FIXABLE: Final = FIXTURES / "fixable"


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def capped(limit: int) -> int:
    """At most ``limit`` examples, and fewer when the profile asks for fewer."""
    return min(int(settings().max_examples), limit)


def copy_tree(source: Path, destination: Path) -> Path:
    """Copy an inventory (or a single fixture file) into a writable directory."""
    destination.mkdir(parents=True, exist_ok=True)
    sources = [source] if source.is_file() else sorted(source.rglob("*"))
    for path in sources:
        if not path.is_file() or path.suffix.lower() not in (".yaml", ".yml"):
            continue
        relative = path.name if source.is_file() else path.relative_to(source).as_posix()
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(path.read_bytes())
    return destination


def findings_of(root: Path) -> list[Finding]:
    return validate(load_tree(root))


def counts(findings: Sequence[Finding]) -> Counter[str]:
    return Counter(finding.rule for finding in findings)


def identities(findings: Sequence[Finding]) -> set[tuple[str, str]]:
    return {(finding.rule, finding.message) for finding in findings}


def offers_in(root: Path, rule: str) -> tuple[Fix, ...]:
    """Every repair offered for the first ``rule`` finding of the tree at ``root``."""
    inventory = load_tree(root)
    for finding in validate(inventory):
        if finding.rule == rule:
            return fixes_for(finding, inventory)
    raise AssertionError(f"no {rule} finding in {root}")


def repaired(root: Path, **kwargs: Any) -> Any:
    """Run the repair loop over ``root`` and commit what it kept."""
    session = EditSession(root=root)
    report = repair(session, **kwargs)
    if report.changed:
        session.commit()
    return report


@pytest.fixture
def fixable(tmp_path: Path) -> Path:
    return copy_tree(FIXABLE, tmp_path / "fixable")


def fixture_tree(tmp_path: Path, name: str) -> Path:
    return copy_tree(INVALID / name, tmp_path / name.removesuffix(".yaml"))


# --------------------------------------------------------------------------- #
# The catalogue
# --------------------------------------------------------------------------- #


def test_every_fix_names_a_rule_that_exists() -> None:
    known = {rule.id for rule in RULES}
    for spec in FIXES:
        assert spec.rule in known, f"{spec.rule} is not a rule"


def test_the_catalogue_has_no_duplicates() -> None:
    ids = [spec.rule for spec in FIXES]
    assert ids == sorted(set(ids), key=ids.index)


def test_a_rule_knows_whether_it_can_be_fixed() -> None:
    fixable_ids = {spec.rule for spec in FIXES}
    for rule in RULES:
        assert rule.fixable is (rule.id in fixable_ids)
        assert (rule.fix is not None) is rule.fixable


def test_the_producer_of_a_rule_is_the_one_the_catalogue_names() -> None:
    for spec in FIXES:
        assert producer_for(spec.rule) is spec.produce
        assert rule_for(spec.rule).fix is spec.produce
    assert producer_for("E002") is None
    assert spec_for("E002") is None


def test_a_summary_is_written_for_a_table_cell() -> None:
    for spec in FIXES:
        assert spec.summary and not spec.summary.endswith("."), spec.rule
        for choice in spec.choices:
            assert choice.summary and not choice.summary.endswith("."), choice.key


def test_a_rule_with_choices_offers_at_least_two() -> None:
    for spec in FIXES:
        assert len(spec.choices) != 1, f"{spec.rule}: one choice is no choice"
        assert spec.is_ambiguous is bool(spec.choices)


# --------------------------------------------------------------------------- #
# What each producer offers
# --------------------------------------------------------------------------- #


def test_a_stale_layout_key_is_dropped(tmp_path: Path) -> None:
    root = fixture_tree(tmp_path, "w138-stale-geometry.yaml")
    (fix,) = offers_in(root, "W138")
    assert fix.key == "prune"
    (operation,) = fix.operations
    assert isinstance(operation, SetGeometry)
    assert operation.view == "l1"
    assert operation.nodes is not None
    assert "sw-gone" not in operation.nodes
    # The entries that survive are carried, not recomputed: a prune that wrote
    # only the removal would leave the rest of the section to be re-emitted.
    assert set(operation.nodes) == {"sw-a", "sw-b"}
    assert operation.edges is None and operation.groups is None


def test_a_loopback_mac_is_unset(tmp_path: Path) -> None:
    root = fixture_tree(tmp_path, "w108-mac-on-loopback.yaml")
    (fix,) = offers_in(root, "W108")
    assert fix.operations == (UnsetField(address="pc-a", path="spec.interfaces[0].mac"),)


def test_an_undeclared_vlan_is_added_to_the_database(tmp_path: Path) -> None:
    root = fixture_tree(tmp_path, "w113-undeclared-vlan.yaml")
    (fix,) = offers_in(root, "W113")
    assert all(isinstance(operation, AppendItem) for operation in fix.operations)
    assert [operation.value for operation in fix.operations] == [  # type: ignore[attr-defined]
        {"id": 20}
    ]
    assert fix.operations[0].path == "spec.vlans"  # type: ignore[attr-defined]


def test_a_native_vlan_offers_both_readings(tmp_path: Path) -> None:
    root = fixture_tree(tmp_path, "w114-native-vlan-not-trunked.yaml")
    listed, dropped = offers_in(root, "W114")
    assert (listed.key, dropped.key) == ("list", "drop")
    assert listed.operations[0].value == "10,20"  # type: ignore[attr-defined]
    assert dropped.operations == (
        UnsetField(address="sw-a", path="spec.interfaces[0].vlan.native_vlan"),
    )


def test_an_unused_vrf_is_removed(tmp_path: Path) -> None:
    root = fixture_tree(tmp_path, "w136-vrf-with-no-interface.yaml")
    (fix,) = offers_in(root, "W136")
    assert fix.key == "drop"
    (operation,) = fix.operations
    assert isinstance(operation, UnsetField)
    # The last entry of the list takes the key with it: 'vrfs: []' says what no
    # key at all says, in a line somebody has to read.
    assert operation.path == "spec.vrfs"


def test_a_departed_member_is_revoked(tmp_path: Path) -> None:
    root = tmp_path / "people"
    root.mkdir()
    (root / "net.yaml").write_text(
        _documents(
            _user("bob", departed=True), _user("ann"), _group("engineering", ["bob", "ann"])
        ),
        encoding="utf-8",
    )
    (fix,) = offers_in(root, "W140")
    assert fix.operations == (UnsetField(address="engineering", path="spec.members[0]"),)


def test_the_last_member_of_a_group_is_not_revoked(tmp_path: Path) -> None:
    """Emptying the group would trade W140 for W139, which is a decision."""
    root = fixture_tree(tmp_path, "w140-departed-member.yaml")
    assert offers_in(root, "W140") == ()


def test_an_unknown_interface_offers_a_repair_per_reading(tmp_path: Path) -> None:
    root = tmp_path / "endpoint"
    root.mkdir()
    (root / "net.yaml").write_text(
        _documents(
            _switch("sw-a", ["GigabitEthernet0/1", "GigabitEthernet0/2"]),
            _computer("pc-a"),
            _cable("cbl-1", "sw-a:GigabitEthernet0/11", "pc-a:eno1"),
        ),
        encoding="utf-8",
    )
    offers = offers_in(root, "E001")
    assert [fix.key for fix in offers] == ["retarget", "declare", "remove"]
    assert offers[0].operations[0].value == "sw-a:GigabitEthernet0/1"  # type: ignore[attr-defined]


def test_an_unknown_element_offers_nothing(tmp_path: Path) -> None:
    """The other branch of E001: nothing in the tree says what was meant."""
    root = fixture_tree(tmp_path, "e001-unknown-endpoint.yaml")
    inventory = load_tree(root)
    findings = [finding for finding in validate(inventory) if finding.rule == "E001"]
    assert findings and all(not fixes_for(finding, inventory) for finding in findings)


def test_a_typo_is_not_guessed_when_two_ports_are_equally_close(tmp_path: Path) -> None:
    """``port3`` is exactly as much like ``port1`` as like ``port2``."""
    root = tmp_path / "ambiguous"
    root.mkdir()
    (root / "net.yaml").write_text(
        _documents(
            _switch("sw-a", ["port1", "port2"]),
            _computer("pc-a"),
            _cable("cbl-1", "sw-a:port3", "pc-a:eno1"),
        ),
        encoding="utf-8",
    )
    assert [fix.key for fix in offers_in(root, "E001")] == ["declare", "remove"]


def test_an_ssid_bridged_into_an_undeclared_vlan_is_repaired(tmp_path: Path) -> None:
    """The other half of W113: a BSS names the VLAN, not the port (§6.2.6)."""
    root = tmp_path / "wireless"
    root.mkdir()
    (root / "net.yaml").write_text(
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: switch\n"
        "metadata:\n  name: ap-a\n"
        "spec:\n"
        "  vlans:\n    - id: 10\n"
        "  interfaces:\n"
        "    - name: wlan0\n      type: wifi\n      mtu: 1500\n"
        "      wireless:\n        role: ap\n        band: 2.4GHz\n        channel: 6\n"
        "        bss:\n          - ssid: guest\n            vlan: 40\n",
        encoding="utf-8",
    )
    (fix,) = offers_in(root, "W113")
    assert [operation.value for operation in fix.operations] == [  # type: ignore[attr-defined]
        {"id": 40}
    ]


def test_a_vlan_finding_pointing_at_neither_shape_offers_nothing(tmp_path: Path) -> None:
    root = fixture_tree(tmp_path, "w113-undeclared-vlan.yaml")
    inventory = load_tree(root)
    finding = next(entry for entry in validate(inventory) if entry.rule == "W113")
    moved = replace(finding, field_path=("spec", "interfaces", 0, "mtu"))
    assert fixes_for(moved, inventory) == ()


def test_a_vrf_something_still_points_at_is_left_alone(tmp_path: Path) -> None:
    """A route in the VRF makes removing it an error, not a repair."""
    root = tmp_path / "vrf"
    root.mkdir()
    (root / "net.yaml").write_text(
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: router\n"
        "metadata:\n  name: rtr-a\n"
        "spec:\n"
        "  vrfs:\n    - name: blue\n      rd: '65001:1'\n"
        "  routes:\n    - prefix: 10.9.0.0/24\n      via: 10.0.0.2\n      vrf: blue\n"
        "  interfaces:\n    - name: eth0\n      type: ethernet\n      mtu: 1500\n"
        "      ipv4:\n        - 10.0.0.1/30\n",
        encoding="utf-8",
    )
    assert offers_in(root, "W136") == ()


def test_an_endpoint_finding_that_names_no_position_offers_nothing(tmp_path: Path) -> None:
    root = tmp_path / "endpointless"
    root.mkdir()
    (root / "net.yaml").write_text(
        _documents(
            _switch("sw-a", ["port1"]),
            _computer("pc-a"),
            _cable("cbl-1", "sw-a:missing", "pc-a:eno1"),
        ),
        encoding="utf-8",
    )
    inventory = load_tree(root)
    finding = next(entry for entry in validate(inventory) if entry.rule == "E001")
    assert fixes_for(replace(finding, field_path=()), inventory) == ()
    assert fixes_for(replace(finding, elements=finding.elements[:1]), inventory) == ()


@pytest.mark.parametrize(
    ("name", "rule"),
    [
        ("w108-mac-on-loopback.yaml", "W108"),
        ("w113-undeclared-vlan.yaml", "W113"),
        ("w114-native-vlan-not-trunked.yaml", "W114"),
        ("w136-vrf-with-no-interface.yaml", "W136"),
        ("w138-stale-geometry.yaml", "W138"),
    ],
)
def test_a_finding_pointing_at_the_wrong_field_offers_nothing(
    tmp_path: Path, name: str, rule: str
) -> None:
    """Totality, one guard deeper: the rule is right and the path is not.

    The shallow version — a finding with no field path at all — is above. This
    one walks each producer past its first guard and into the ones that read the
    document, which is where a stale finding from a tree that has moved lands.
    """
    root = fixture_tree(tmp_path, name)
    inventory = load_tree(root)
    finding = next(entry for entry in validate(inventory) if entry.rule == rule)
    assert fixes_for(finding, inventory), "the fixture must produce a repairable finding"
    for path in (
        ("spec", "interfaces", 99, "mac"),
        ("spec", "interfaces", "x", "vlan"),
        ("spec", "views", "l1", "nodes"),
        ("spec", "vrfs", "x"),
        ("spec", "members", 99),
        ("spec", "elsewhere"),
    ):
        assert fixes_for(replace(finding, field_path=path), inventory) == (), path


def test_a_producer_survives_a_finding_from_another_tree(tmp_path: Path) -> None:
    """Totality: a finding may outlive the tree it was found in."""
    stale = findings_of(fixture_tree(tmp_path, "w138-stale-geometry.yaml"))
    empty = Inventory(root=tmp_path)
    for finding in stale:
        assert fixes_for(finding, empty) == ()


def test_a_producer_ignores_a_finding_whose_field_path_is_wrong() -> None:
    """A malformed finding is not a crash; it is a rule with nothing to offer."""
    empty = Inventory(root=Path("."))
    for spec in FIXES:
        finding = Finding(rule=spec.rule, severity=rule_for(spec.rule).severity, message="x")
        assert tuple(spec.produce(finding, empty)) == ()


# --------------------------------------------------------------------------- #
# The loop
# --------------------------------------------------------------------------- #


def test_every_unambiguous_fix_is_applied_and_the_ambiguous_one_is_not(fixable: Path) -> None:
    before = findings_of(fixable)
    report = repaired(fixable)

    assert [entry.finding.rule for entry in report.applied] == ["W138", "W108", "W113"]
    assert [entry.finding.rule for entry in report.skipped] == ["W114"]
    assert "--choose W114=" in report.skipped[0].reason
    assert counts(findings_of(fixable)) == Counter({"W114": 1})
    assert len(before) == 4


def test_a_chosen_repair_is_applied_like_any_other(fixable: Path) -> None:
    report = repaired(fixable, choices={"W114": "list"})
    assert [entry.fix.key for entry in report.applied] == ["prune", "drop", "declare", "list"]
    assert findings_of(fixable) == []


def test_two_findings_in_one_document_do_not_undo_each_other(tmp_path: Path) -> None:
    """Both stale keys go, which one pass computed from the same tree could not."""
    root = tmp_path / "two"
    root.mkdir()
    (root / "net.yaml").write_text(
        _documents(
            _switch("sw-a", ["port1"]),
            _layout({"sw-a": [0, 0], "gone-a": [1, 1], "gone-b": [2, 2]}),
        ),
        encoding="utf-8",
    )
    before = counts(findings_of(root))
    report = repaired(root)
    assert [entry.fix.key for entry in report.applied] == ["prune", "prune"]
    text = (root / "net.yaml").read_text(encoding="utf-8")
    assert "gone-a" not in text and "gone-b" not in text and "sw-a" in text
    assert counts(findings_of(root)) == before - Counter({"W138": 2})


def test_a_repair_that_would_make_things_worse_is_rolled_back(tmp_path: Path) -> None:
    """Removing the cable is a real repair, and here it orphans a device."""
    root = tmp_path / "orphan"
    root.mkdir()
    text = _documents(
        _switch("sw-a", ["port1"]),
        _computer("pc-a"),
        _cable("cbl-1", "sw-a:missing", "pc-a:eno1"),
    )
    (root / "net.yaml").write_text(text, encoding="utf-8")

    session = EditSession(root=root)
    report = repair(session, choices={"E001": "remove"})
    assert report.applied == ()
    assert {entry.finding.rule for entry in report.skipped} == {"E001"}
    assert "W103" in " ".join(str(finding) for finding in report.skipped[0].introduced)
    # Rolled back to the byte: the session has nothing pending, so nothing is
    # written and no file shows an empty diff.
    assert session.changes == {}
    assert report.diff == ""
    assert (root / "net.yaml").read_text(encoding="utf-8") == text


def test_a_repair_the_write_path_refuses_is_reported_not_raised(tmp_path: Path) -> None:
    """``declare`` on a device that cannot take the port: reported, not a crash."""
    root = tmp_path / "refused"
    root.mkdir()
    (root / "net.yaml").write_text(
        _documents(
            _switch("sw-a", ["port1"]),
            _computer("pc-a"),
            _cable("cbl-1", "sw-a:port1", "pc-a:eno1"),
            _adapter("adp-a", "pc-a"),
            _cable("cbl-2", "adp-a:missing", "sw-a:port1"),
        ),
        encoding="utf-8",
    )
    session = EditSession(root=root)
    report = repair(session, choices={"E001": "declare"})
    assert report.applied == () or report.skipped
    assert not any("Traceback" in entry.reason for entry in report.skipped)


def test_a_repair_that_fails_halfway_leaves_no_trace_of_its_first_half(
    fixable: Path,
) -> None:
    """A batch is atomic per operation; a *repair* has to be atomic as a whole."""
    inventory = load_tree(fixable)
    finding = next(entry for entry in validate(inventory) if entry.rule == "W113")
    (declare,) = fixes_for(finding, inventory)
    broken = Fix(
        declare.key,
        declare.title,
        (declare.operations[0], UnsetField(address="sw-a", path="spec.nothing")),
    )
    session = EditSession(root=fixable)
    with pytest.raises(EditError):
        apply_fix(session, finding, broken)
    assert session.changes == {}


def test_a_dry_run_writes_nothing_and_still_reports_the_diff(fixable: Path) -> None:
    before = (fixable / "layout.yaml").read_text(encoding="utf-8")
    session = EditSession(root=fixable)
    report = repair(session)
    assert report.diff.startswith("--- a/layout.yaml")
    assert (fixable / "layout.yaml").read_text(encoding="utf-8") == before
    assert set(report.changes) == {"layout.yaml", "switches.yaml"}


def test_the_report_has_a_json_form(fixable: Path) -> None:
    payload = repaired(fixable).to_dict()
    assert [entry["rule"] for entry in payload["applied"]] == ["W138", "W108", "W113"]
    assert payload["applied"][0]["operations"][0]["op"] == "set-geometry"
    assert payload["skipped"][0]["choices"] == [
        {"key": "list", "title": payload["skipped"][0]["choices"][0]["title"]},
        {"key": "drop", "title": payload["skipped"][0]["choices"][1]["title"]},
    ]
    assert payload["files"] == {"layout.yaml": "written", "switches.yaml": "written"}


def test_a_clean_inventory_is_left_alone(tmp_path: Path) -> None:
    root = copy_tree(EXAMPLES / "home-lab", tmp_path / "home-lab")
    report = repaired(root)
    assert report.applied == () and report.skipped == ()
    assert report.diff == ""


def test_apply_fix_leaves_the_session_holding_a_repair_that_stands(fixable: Path) -> None:
    inventory = load_tree(fixable)
    finding = next(entry for entry in validate(inventory) if entry.rule == "W108")
    (fix,) = fixes_for(finding, inventory)
    session = EditSession(root=fixable)
    outcome = apply_fix(session, finding, fix)
    assert outcome.kept and outcome.files == ("switches.yaml",)
    assert session.changes


def test_offers_can_be_limited(fixable: Path) -> None:
    inventory = load_tree(fixable)
    assert len(offers_for(validate(inventory), inventory, limit=2)) == 2


# --------------------------------------------------------------------------- #
# The invariant
# --------------------------------------------------------------------------- #


def inventories() -> Iterator[Path]:
    """Every inventory in the repository that a fix run can be aimed at."""
    yield from sorted(path for path in EXAMPLES.iterdir() if path.is_dir())
    yield FIXABLE
    yield from sorted(INVALID.glob("*.yaml"))


@pytest.mark.parametrize("source", list(inventories()), ids=lambda path: path.name)
def test_repairing_an_inventory_never_introduces_a_finding(source: Path, tmp_path: Path) -> None:
    """The promise, over everything in the repository.

    Not "the tree ends up clean" — most of these fixtures are broken in ways
    nothing can repair — but "no rule reports more than it did", which is the
    statement ``--fix`` makes and the only one it can keep.
    """
    root = copy_tree(source, tmp_path / "tree")
    before = counts(findings_of(root))
    report = repaired(root)

    after = counts(findings_of(root))
    for rule, count in after.items():
        assert count <= before[rule], f"{rule} went from {before[rule]} to {count}"
    # And what was applied actually repaired what it named.
    standing = identities(findings_of(root))
    for entry in report.applied:
        assert (entry.finding.rule, entry.finding.message) not in standing


@pytest.mark.parametrize("source", list(inventories()), ids=lambda path: path.name)
def test_the_written_tree_is_the_one_the_dry_run_promised(source: Path, tmp_path: Path) -> None:
    root = copy_tree(source, tmp_path / "tree")
    promised = repair(EditSession(root=root)).changes
    repaired(root)
    for relative, text in promised.items():
        path = root / relative
        assert (None if not path.is_file() else path.read_text(encoding="utf-8")) == text


def test_every_fixable_rule_is_tested_by_name() -> None:
    """No producer joins the catalogue without a test of its own here.

    A cheap gate rather than a clever one: the expensive version — run every
    fixture past every producer and insist each one fired — is the invariant
    tests above, and they do not say *which* producer went untested.
    """
    source = Path(__file__).read_text(encoding="utf-8")
    for spec in FIXES:
        assert f'"{spec.rule}"' in source, f"{spec.rule} has no test of its own"


# --------------------------------------------------------------------------- #
# The invariant, over inventories nobody wrote
# --------------------------------------------------------------------------- #


@given(
    plan=ng.inventory_plans(),
    stale=st.lists(st.sampled_from(["ghost-a", "ghost-b"]), min_size=1, max_size=2),
)
@settings(
    # Each example writes a tree, validates it three times over and writes it
    # again, so this is one of the properties that is capped in absolute terms
    # as well as by the profile. See ``capped()`` in tests/test_properties.py.
    max_examples=capped(50),
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.function_scoped_fixture],
)
def test_a_fix_never_introduces_a_finding(
    tmp_path_factory: pytest.TempPathFactory, plan: ng.InventoryPlan, stale: list[str]
) -> None:
    """The invariant, on generated inventories spoiled with a fixable defect.

    A generated inventory is *valid*, so on its own it would exercise the loop's
    empty path and nothing else. Adding a layout document that places elements
    nobody declared guarantees at least one repair per run, and leaves whatever
    findings the generator happened to produce to be quantified over as well.
    """
    root = plan.write(tmp_path_factory.mktemp("fixes"))
    (root / "layout.yaml").write_text(
        _layout({name: [index * 10, 0] for index, name in enumerate(dict.fromkeys(stale))}),
        encoding="utf-8",
    )
    inventory = load_tree(root)
    assume(not inventory.errors)
    before = counts(validate(inventory))

    session = EditSession(root=root)
    report = repair(session)
    assert report.applied, "the stale geometry must have been repaired"
    if report.changed:
        session.commit()

    after = validate(load_tree(root))
    for rule, count in counts(after).items():
        assert count <= before[rule], f"{rule} went from {before[rule]} to {count}"
    standing = identities(after)
    for entry in report.applied:
        assert (entry.finding.rule, entry.finding.message) not in standing


# --------------------------------------------------------------------------- #
# Documents, written the way the fixtures write them
# --------------------------------------------------------------------------- #


def _documents(*documents: str) -> str:
    return "---\n".join(documents)


def _switch(name: str, ports: Sequence[str]) -> str:
    interfaces = "".join(
        f"    - name: {port}\n      type: ethernet\n      mtu: 1500\n" for port in ports
    )
    return (
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: switch\n"
        f"metadata:\n  name: {name}\n"
        f"spec:\n  interfaces:\n{interfaces}"
    )


def _computer(name: str) -> str:
    return (
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: computer\n"
        f"metadata:\n  name: {name}\n"
        "spec:\n  interfaces:\n    - name: eno1\n      type: ethernet\n      mtu: 1500\n"
        "      ipv4:\n        - 10.0.0.9/24\n"
    )


def _adapter(name: str, host: str) -> str:
    return (
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: adapter\n"
        f"metadata:\n  name: {name}\n"
        f"spec:\n  upstream:\n    attached_to: {host}\n  ports: 1\n"
        "  interfaces:\n    - name: eth0\n      type: ethernet\n      mtu: 1500\n"
    )


def _cable(name: str, first: str, second: str) -> str:
    return (
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: cable\n"
        f"metadata:\n  name: {name}\n"
        f"spec:\n  endpoints:\n    - {first}\n    - {second}\n  medium: copper\n"
    )


def _user(name: str, *, departed: bool = False) -> str:
    status = "  status: departed\n" if departed else ""
    return (
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: user\n"
        f"metadata:\n  name: {name}\n"
        f"spec:\n  full_name: {name.title()} Example\n{status}"
    )


def _group(name: str, members: Sequence[str]) -> str:
    listed = "".join(f"    - {member}\n" for member in members)
    return (
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: group\n"
        f"metadata:\n  name: {name}\n"
        f"spec:\n  members:\n{listed}"
    )


def _layout(nodes: dict[str, Sequence[int]]) -> str:
    placed = "".join(
        f"        {name}: {{position: [{point[0]}, {point[1]}]}}\n" for name, point in nodes.items()
    )
    return (
        "apiVersion: netgraph.dev/v1alpha1\n"
        "kind: layout\n"
        "metadata:\n  name: default\n"
        f"spec:\n  views:\n    l1:\n      nodes:\n{placed}"
    )
