"""The provenance banner every artefact carries, where its syntax allows one.

An exported file lands somewhere it will be found again months later, usually by
somebody who did not run the command. Three questions have to be answerable
from the file itself: *what wrote this*, *may I edit it*, and *what is it not
telling me*. Anything else — a timestamp, a hostname, an absolute path — is left
out on purpose: it would make two exports of an unchanged inventory differ, and
the whole point of these emitters is that their output is diffable.

Not every format has somewhere to put it. ``hosts`` and ``dns-zone`` take
comments, Markdown takes an HTML comment, and CSV and JSON take none at all —
RFC 4180 has no comment syntax, and a JSON document with a stray key is a JSON
document some consumer will choke on. The two JSON emitters therefore carry
their provenance *inside* the schema, in a field the consumer already ignores;
see :mod:`netgraph.export.ansible` and :mod:`netgraph.export.prometheus`.
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator

from netgraph import __version__

__all__ = ["GENERATOR", "comment_header", "html_header"]

#: What wrote the file. The version is included deliberately: a stale artefact
#: is the failure mode these exports have, and "which netgraph wrote this" is
#: the first question when one turns up. It is not machine-specific, so two
#: checkouts at the same version still produce identical bytes.
GENERATOR = f"netgraph {__version__}"


def comment_header(marker: str, export_format: str, notes: Iterable[str] = ()) -> Iterator[str]:
    """The banner as comment lines introduced by ``marker``.

    Args:
        marker: ``#`` for a hosts file, ``;`` for a zone file.
        export_format: The ``netgraph export`` format, so the reader can
            reproduce the file with one command.
        notes: What this format drops, in the caller's words. Written into the
            banner rather than into the docs alone: the person holding a
            generated file rarely has the docs open.
    """
    yield f"{marker} Generated by 'netgraph export {export_format}' -- do not edit."
    yield f"{marker} {GENERATOR}. Re-run the command to regenerate from the inventory."
    for note in notes:
        yield f"{marker} {note}" if note else marker
    yield marker


def html_header(export_format: str, notes: Iterable[str] = ()) -> Iterator[str]:
    """The same banner as an HTML comment, for Markdown output."""
    yield "<!--"
    yield f"Generated by 'netgraph export {export_format}' -- do not edit."
    yield f"{GENERATOR}. Re-run the command to regenerate from the inventory."
    yield from notes
    yield "-->"
    yield ""
