"""The shipped ``netviz.netviz`` collection: where it is, and how to install it.

Ansible finds a collection by directory: somewhere on its collections path there
has to be ``ansible_collections/<namespace>/<name>/``, and inside that a
``plugins/`` tree. So the collection ships *inside the wheel*, laid out exactly
that way, and there are two ways to point Ansible at it:

**Name the path.** ``ANSIBLE_COLLECTIONS_PATH=$(netviz ansible path)`` — nothing
is copied, and the collection is by construction the one belonging to the netviz
that is installed. Upgrading netviz upgrades the plugins.

**Copy it.** ``netviz ansible install`` writes the tree into
``~/.ansible/collections`` (or anywhere else), which is what a control node with
its own collections path and a ``requirements.yml`` habit expects. A copy can go
stale against the netviz beside it, so what is written records the version it
came from.

``galaxy.yml`` is *generated* rather than shipped, and that is the reason: it
carries a version, netviz already has one, and a second copy of a version number
in a file nobody looks at is a copy that will be wrong. Ansible does not need it
to load a collection from a path — it is metadata for building and listing — so
the tree in the wheel does without, and an install writes one naming the netviz
it was installed from.
"""

from __future__ import annotations

import shutil
from collections.abc import Iterator
from pathlib import Path
from typing import Final

from netviz import __version__
from netviz.errors import NetvizError
from netviz.fsio import write_text

__all__ = [
    "COLLECTION",
    "DEFAULT_DESTINATION",
    "NAMESPACE",
    "collection_path",
    "collections_path",
    "galaxy_manifest",
    "install",
]

#: The collection's two names, as ``netviz.netviz.query`` spells them.
NAMESPACE: Final = "netviz"
COLLECTION: Final = "netviz"

#: Where ``ansible-galaxy`` installs by default, and therefore where this does.
DEFAULT_DESTINATION: Final = Path("~/.ansible/collections")

#: The directory inside the package that *is* a collections path.
_ROOT: Final = Path(__file__).parent / "collections"


def collections_path() -> Path:
    """The path to put on ``ANSIBLE_COLLECTIONS_PATH``.

    A directory holding ``ansible_collections/``, which is what that variable
    means — not the collection itself.
    """
    return _ROOT


def collection_path() -> Path:
    """The collection's own directory, the one an install copies."""
    return _ROOT / "ansible_collections" / NAMESPACE / COLLECTION


def galaxy_manifest() -> str:
    """``galaxy.yml`` for the collection, naming the netviz it came from.

    Written on install rather than shipped, so the version cannot disagree with
    :data:`netviz.version.__version__`.
    """
    return "\n".join(
        (
            "# Generated by 'netviz ansible install'. The version is the netviz",
            "# this collection was installed from; reinstall after upgrading.",
            f"namespace: {NAMESPACE}",
            f"name: {COLLECTION}",
            f"version: {__version__}",
            "readme: README.md",
            "authors:",
            "  - netviz contributors",
            'description: "Query a netviz inventory from Ansible: dynamic inventory,'
            ' lookups and filters."',
            "license:",
            "  - MIT",
            "tags:",
            "  - networking",
            "  - inventory",
            "  - infrastructure",
            "repository: https://github.com/blechschmidt/netviz",
            "documentation: https://github.com/blechschmidt/netviz/blob/main/docs/ansible.md",
            "issues: https://github.com/blechschmidt/netviz/issues",
            "build_ignore:",
            "  - __pycache__",
            "",
        )
    )


def install(destination: Path | str | None = None, *, force: bool = False) -> list[Path]:
    """Copy the collection under ``destination``, and say what was written.

    Args:
        destination: A *collections path* — the directory that holds
            ``ansible_collections/``. Defaults to
            :data:`DEFAULT_DESTINATION`.
        force: Overwrite an installation that is already there. Without it, a
            directory that exists is refused rather than merged: a merge would
            leave a plugin from an older netviz sitting beside one from this
            one, and the older would keep answering.

    Returns:
        Every file written, in the order it was written, ``galaxy.yml`` last.

    Raises:
        NetvizError: The target exists and ``force`` was not given.
    """
    target = Path(destination or DEFAULT_DESTINATION).expanduser()
    into = target / "ansible_collections" / NAMESPACE / COLLECTION
    if into.exists():
        if not force:
            raise NetvizError(
                f"{into} already exists; pass force to replace it, or install somewhere else"
            )
        shutil.rmtree(into)

    written: list[Path] = []
    for source in _sources():
        relative = source.relative_to(collection_path())
        copy = into / relative
        copy.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, copy)
        written.append(copy)
    manifest = into / "galaxy.yml"
    # Through :mod:`netviz.fsio`, which translates no line endings: this file is
    # read by ansible-galaxy and may well be committed, and a copy that is LF on
    # one control node and CRLF on another is a diff nobody made.
    write_text(manifest, galaxy_manifest())
    written.append(manifest)
    return written


def _sources() -> Iterator[Path]:
    """Every file of the shipped collection, in a stable order.

    Compiled Python is skipped: an installed collection is loaded by a different
    interpreter than the one that wrote it, and a ``__pycache__`` copied out of a
    wheel is at best ignored and at worst stale.
    """
    for path in sorted(collection_path().rglob("*")):
        if path.is_file() and "__pycache__" not in path.parts:
            yield path
