"""The banner every generated configuration file carries.

A device configuration ends up somewhere far more dangerous than an
``/etc/hosts`` fragment: on a box, under ``/etc``, next to a file somebody
hand-edited last year. The banner therefore answers one more question than
:mod:`netgraph.export.header` does — *which inventory documents is this the
shadow of* — and it answers it in a form both a person and netgraph can read.

The ``netgraph-*`` keys are the machine-readable half. ``netgraph drift`` reads
the same seven dialects back (:mod:`netgraph.importer`), and a file that says which
dialect it is and which element it describes needs neither ``--from`` nor
``--host``::

    netgraph export netplan --name pc-desk -o /tmp/pc-desk.yaml
    netgraph drift /tmp/pc-desk.yaml          # dialect and host read from the banner

A running configuration collected off a real device has no banner, and the
sniffer falls back to the shape of the file; the keys are what makes the
*generated* half of the round trip exact rather than merely likely.

Nothing here is derived from the clock, the host or the path the command ran in,
for the same reason the other emitters leave them out: two exports of an
unchanged inventory have to be byte-identical, or a diff in a generated file
stops meaning "the network changed".
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator

from netgraph.banner import DIALECT_KEY, ELEMENT_KEY, SOURCE_KEY, parse_banner
from netgraph.export.config.plan import DevicePlan
from netgraph.export.header import GENERATOR

__all__ = [
    "DIALECT_KEY",
    "ELEMENT_KEY",
    "SOURCE_KEY",
    "config_header",
    "parse_banner",
]


def config_header(
    marker: str,
    dialect: str,
    plan: DevicePlan,
    *,
    notes: Iterable[str] = (),
) -> Iterator[str]:
    """The banner as comment lines introduced by ``marker``.

    Args:
        marker: ``#`` for YAML, INI and shell-comment formats; ``!`` for FRR.
        dialect: The ``netgraph export`` format that wrote the file.
        plan: The device it describes.
        notes: What this dialect could not carry for *this* device, in the
            dialect's own words. Written into the file rather than into the
            manifest alone: the person holding a generated ``/etc/frr/frr.conf``
            is rarely the person who ran the export.
    """
    yield f"{marker} Generated by 'netgraph export {dialect}' -- do not edit."
    yield f"{marker} {GENERATOR}. Re-run the command to regenerate from the inventory."
    yield f"{marker} {DIALECT_KEY}: {dialect}"
    yield f"{marker} {ELEMENT_KEY}: {plan.fqn} ({plan.kind})"
    for source in plan.sources:
        yield f"{marker} {SOURCE_KEY}: {source}"
    if not plan.sources:  # pragma: no cover - every loaded element has a source
        yield f"{marker} {SOURCE_KEY}: <not recorded>"
    for note in notes:
        yield f"{marker} {note}" if note else marker
    yield marker
